server:
  port: 1001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quizz
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    connection-test-query: SELECT 1
#    test-while-idle: true
#    test-on-borrow: true
#    validation-interval: 10000
#    log-validation-errors: true
#    validation-query: SELECT 1
#    hikari:
#      connection-timeout: 30000
#      max-lifetime: 10800000
#      maximum-pool-size: 1
#      minimum-pool-size: 1


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update